
  kind: pipeline
  name: nodeEval

  steps:
  - name: nodeTest
    image: node
    commands:
      - sleep 15
      - npm install -g mysql
      - mysql --version
      - npm install
      - npm install -g mocha
      - npm -g install chai
      - npm -g install chai-http
      - npm -g install mochawesome
      - mocha test.js --reporter mochawesome --exit


services:
- name: database
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: hackathon2308